# Generated by Django 5.0.7 on 2024-07-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dishId', models.AutoField(primary_key=True, serialize=False)),
                ('dishName', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=300)),
                ('isPublished', models.BooleanField()),
            ],
        ),
    ]
